server:
  port: 8090
  servlet:
    session:
      timeout: 2000m   # Срок жизни сессии — 2000 минут
      cookie:
        secure: false  # Разрешить отправку cookie через HTTP

spring:
  application:
    name: cdo-back
  oauth2:
    client:
      registration:
        keycloak:
          client-id: cdo-client
          client-secret: 73e57f27-ed7f-4d74-ad71-9e9f99b36bbf
          authorization-grant-type: authorization_code
          redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
          scope: openid,profile,email
        jwt:
          issuer-uri: http://localhost:8091/realms/cdo-realm
      provider:
        keycloak:
          issuer-uri: http://localhost:8091/realms/cdo-realm
          user-name-attribute: preferred_username

  datasource:
    url: jdbc:mariadb://localhost:3306/cdo
    username: vd
    password: 111
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
jwt:
  secret: yourSecretKeyHere
