server:
  port: 8090
  servlet:
    session:
      timeout: 2000m   # Срок жизни сессии — 2000 минут
      cookie:
        http-only: false
        secure: false  # Разрешить отправку cookie через HTTP
        same-site: Lax
spring:
  application:
    name: cdo-back

  datasource:
    url: jdbc:mariadb://localhost:3306/cdo
    username: vd
    password: 111
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8091/realms/cdo-realm
          jwk-set-uri: http://localhost:8091/realms/cdo-realm/protocol/openid-connect/certs
