server:
  port: 8090
  servlet:
    session:
      timeout: 2000m   # Срок жизни сессии — 2000 минут
      cookie:
        secure: false  # Разрешить отправку cookie через HTTP

spring:
  application:
    name: cdo-back

  datasource:
    url: jdbc:mariadb://localhost:3306/cdo
    username: vd
    password: 111
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8091/realms/cdo-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: cdo-client
            client-secret: QDytipc4kKuGRWG8oQRwIBLvhv9DKhrf
            scope: openid, profile, cdo-scope, microprofile-jwt
            authorization-grant-type: authorization_code
